// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1694771411);
user_pref("browser.search.region", "UA");
user_pref("calendar.caldav.googleResync", 1694771410);
user_pref("calendar.list.sortOrder", "c2560bc6-e856-4e54-9345-fe450fb2c9f5");
user_pref("calendar.registry.c2560bc6-e856-4e54-9345-fe450fb2c9f5.calendar-main-default", true);
user_pref("calendar.registry.c2560bc6-e856-4e54-9345-fe450fb2c9f5.calendar-main-in-composite", true);
user_pref("calendar.registry.c2560bc6-e856-4e54-9345-fe450fb2c9f5.disabled", true);
user_pref("calendar.registry.c2560bc6-e856-4e54-9345-fe450fb2c9f5.name", "Home");
user_pref("calendar.registry.c2560bc6-e856-4e54-9345-fe450fb2c9f5.type", "storage");
user_pref("calendar.registry.c2560bc6-e856-4e54-9345-fe450fb2c9f5.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Kyiv");
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1694771408);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230826133440");
user_pref("extensions.lastAppVersion", "102.15.0");
user_pref("extensions.lastPlatformVersion", "102.15.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"3c2dfbdf-91e2-4f6e-b365-77e5f77a9a6a\",\"google@search.mozilla.org\":\"fe6e6c3e-7a30-42ad-9837-a1b583f145f0\",\"ddg@search.mozilla.org\":\"e10a0423-e1e5-47bb-b02e-80af185217cc\",\"amazondotcom@search.mozilla.org\":\"04436d7a-e3c5-4771-830f-55a194f8364c\",\"wikipedia@search.mozilla.org\":\"4a3e7919-304c-447f-94ae-cb585a629b81\",\"bing@search.mozilla.org\":\"85c29c6b-2c6e-4e9b-bb3e-e33766f6b249\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "7747a8c8-8098-4555-a2b8-032cde71f9d");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.15.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "659bd358-4f80-4b57-bc77-55e015bdc24c");
user_pref("toolkit.telemetry.previousBuildID", "20230826133440");
